openapi: 3.0.3
info:
  title: Totem Food Service - OpenAPI 3.0
  description: |-
    API utilizada pelo Administrativo e aplicação hospedada no Totem da Food Service
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: Category
    description: Access to Product categories
paths:
  /administrative/category:
    post:
      tags:
        - Category
      summary: Create a new category
      description: Create a new category
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreateDto'
      responses:
        '201':
          description: created operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'
        '405':
          description: Invalid input
components:
  schemas:
    CategoryDto:
      type: object
      properties:
        id:
          type: string
          example: '64826bb3554280604d93d7b6'
        name:
          type: string
          description: Category name
          example: 'refrigerantes'
        modifiedAt:
          type: string
          format: date-time
          example: '2023-06-09T00:00:51.623596531Z'
          description: Date of last update
        createAt:
          type: string
          format: date-time
          example: '2023-06-09T00:00:51.623596531Z'
          description: Date of creation
    CategoryCreateDto:
      type: object
      properties:
        name:
          type: string
          description: Category name
          example: 'refrigerantes'