version: '3.5'

networks:
  developer-network:
    driver: bridge

services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MY_MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MY_MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "${MY_MONGO_PORT}:27017"
    volumes:
      - ${MY_VOLUME_DATA}/mongo/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo-dev:27017/test --quiet
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 5s
    networks:
      - developer-network

  totem-food-service:
    container_name: totem-food-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING.DATA.MONGODB.HOST: mongo-dev
      SPRING.DATA.MONGODB.PORT: 27017
      SPRING.DATA.MONGODB.DATABASE: totem-food
      SPRING.DATA.MONGODB.USERNAME: root
      SPRING.DATA.MONGODB.PASSWORD: qwe123
      SPRING.DATA.MONGODB.AUTHENTICATION_DATABASE: admin
      PAYMENT_GATEWAY_URL: http://payment-gateway:5000/v1/online-payment
    ports:
      - "8080:8080"
    depends_on:
      mongo-dev:
        condition: service_healthy
    networks:
      - developer-network

  payment-gateway:
    container_name: payment-gateway
    build:
      context: ./mock-payment-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mock-payment-gateway/mocks:/app/mocks
    networks:
      - developer-network