replicaCount: 1

image:
  repository: jeffersoncleyson/totem-food-service
  tag: "temporary"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

loadBalancer:
  totem_food:
    createPublicLB: false

secrets:
  database:
    host: mongo-mongodb-service.totem-apps.svc.cluster.local
    port: 27017
    dbname: totem-food
    username: root
    password: qwe123
    auth: admin
  email:
    host: mailhog-mailhog-service.totem-apps.svc.cluster.local
    port: 1025
    username: username
    password: password
    auth:
      enabled: false
    tls:
      enabled: false
    email: contato@totem.food.service.com.br
  payment:
    gateway:
      url: http://payment-payment-gateway-service.totem-apps.svc.cluster.local:5000/v1/online-payment
  cognito:
    userPoolId: userPoolId
    clientId: clientId
    clientSecret: clientSecret

## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
ingress:
  path:
    value: /v1
    type: Prefix

hpa:
  min_replicas: 1
  max_replicas: 10
  target:
    avg:
      memory: 50
      cpu: 50

env:
  name: dev
