apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
    app.kubernetes.io/name: {{ .Release.Name }}-mongodb
spec:
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
    app.kubernetes.io/name: {{ .Release.Name }}-mongodb
  type: {{ .Values.service.type }}
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
