apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-mongodb-secrets
    app.kubernetes.io/name: {{ .Release.Name }}-mongodb-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.root.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.root.password }}