apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-payment-gateway-configmap
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-payment-gateway
    app.kubernetes.io/name: {{ .Release.Name }}-payment-gateway
data:
  mock.json: |
    [
      {
        "request": {
          "method": "POST",
          "path": "/v1/online-payment"
        },
        "response": {
          "body": {
            "qrcodeBase64": "iVBORw0KGgoAAAANSUhEUgAABRQAAAUUCAYAAACu5p7oAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAIABJREFUeJzs2luO3LiWQNFmI+Y/Zd6vRt36KGNXi7ZOBtcagHD4kNLeiLX33v8DAAAAABD879sDAAAAAAA/h6AIAAAAAGSCIgAAAACQCYoAAAAAQCYoAgAAAACZoAgAAAAAZIIiAAAAAJAJigAAAABAJigCAAAAAJmgCAAAAABkgiIAAAAAkAmKAAAAAEAmKAIAAAAAmaAIAAAAAGSCIgAAAACQCYoAAAAAQCYoAgAAAACZoAgAAAAAZIIiAAAAAJAJigAAAABAJigCA...",
            "qrcode": "00020126600014br.gov.bcb.pix0117test@testuser.com0217dados adicionais520400005303986540510.005802BR5913Maria Silva6008Brasilia62070503***6304E2CA"
          },
          "status_code": 200
        }
      }
    ]