server:
  port: 8081

logging:
  level:
    root: ${LOGGING_LEVEL:info}
    "[com.totem.food]": ${APP_LOGGING_LEVEL:debug}
    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": ${SHOW_ENDPOINTS_LOGGING_LEVEL:info}
  pattern:
    level: "%clr(${LOG_LEVEL_PATTERN: [%X{x-request-id}] [%X{x-environment-id}] [%X{x-customer-id}] -%5p})"

spring:
  jackson:
    default-property-inclusion: non_null

app:
  version: ^project.version^
  name: ^project.name^
  description: ^project.description^
  inspect_beans: ${INSPECT_BEANS:false}


cognito:
  userPool:
    id: ${COGNITO_USER_POOL_ID:}
    clientId: ${COGNITO_CLIENT_ID:}
    clientSecret: ${COGNITO_CLIENT_SECRET:}