apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailhog-service-lb
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-mailhog
    app.kubernetes.io/name: {{ .Release.Name }}-mailhog
spec:
  ports:
    - name: dashboard
      protocol: TCP
      port: 8085
      targetPort: dashboard
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-mailhog
    app.kubernetes.io/name: {{ .Release.Name }}-mailhog
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
