apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-totem-food-database-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
    app.kubernetes.io/name: {{ .Release.Name }}-totem-food
type: Opaque
stringData:
  SPRING_DATA_MONGODB_HOST: {{ .Values.secrets.database.host }}
  SPRING_DATA_MONGODB_PORT: "{{ .Values.secrets.database.port }}"
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.secrets.database.dbname }}
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.secrets.database.username }}
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.secrets.database.password }}
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: {{ .Values.secrets.database.auth }}