apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-totem-food-cognito-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
    app.kubernetes.io/name: {{ .Release.Name }}-totem-food
type: Opaque
stringData:
  COGNITO_USER_POOL_ID: {{ .Values.secrets.cognito.userPoolId }}
  COGNITO_CLIENT_ID: {{ .Values.secrets.cognito.clientId }}
  COGNITO_CLIENT_SECRET: {{ .Values.secrets.cognito.clientSecret }}