apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
    app.kubernetes.io/name: {{ .Release.Name }}-totem-food
  name: {{ .Release.Name }}-totem-food
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
      app.kubernetes.io/name: {{ .Release.Name }}-totem-food
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-totem-food
        app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
        app.kubernetes.io/name: {{ .Release.Name }}-totem-food
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-totem-food-database-secrets
          - secretRef:
              name: {{ .Release.Name }}-totem-food-email-secrets
          - secretRef:
              name: {{ .Release.Name }}-totem-food-payment-secrets
          - secretRef:
              name: {{ .Release.Name }}-totem-food-cognito-secrets
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
